# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Deltoid.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator, QIcon
from PyQt5.QtWidgets import QMessageBox


class Ui_Deltoid(object):
    def setupUi(self, Deltoid):
        Deltoid.setObjectName("Deltoid")
        Deltoid.resize(300, 300)
        Deltoid.setMinimumSize(QtCore.QSize(300, 300))
        Deltoid.setMaximumSize(QtCore.QSize(300, 300))
        Deltoid.setWindowIcon(QIcon('logo.png'))
        Deltoid.setStyleSheet("background-image: url(tlopodstrony.png);")

        self.label = QtWidgets.QLabel(Deltoid)
        self.label.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.label.setStyleSheet("background:rgb(255, 255, 255)")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        #self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setWordWrap(False)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")

        self.obliczButton = QtWidgets.QPushButton(Deltoid)
        self.obliczButton.setGeometry(QtCore.QRect(100, 180, 93, 28))
        self.obliczButton.setStyleSheet("background:rgb(255, 255, 255)")
        self.obliczButton.setObjectName("obliczButton")

        self.label_2 = QtWidgets.QLabel(Deltoid)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 101, 31))
        self.label_2.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        #self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(1)
        self.label_2.setMidLineWidth(0)
        self.label_2.setWordWrap(False)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(Deltoid)
        self.label_3.setGeometry(QtCore.QRect(170, 220, 121, 31))
        self.label_3.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        #self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setLineWidth(1)
        self.label_3.setMidLineWidth(0)
        self.label_3.setWordWrap(False)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")

        self.lcdPole = QtWidgets.QLCDNumber(Deltoid)
        self.lcdPole.setGeometry(QtCore.QRect(40, 262, 71, 31))
        self.lcdPole.setObjectName("lcdPole")

        self.lcdObwod = QtWidgets.QLCDNumber(Deltoid)
        self.lcdObwod.setGeometry(QtCore.QRect(190, 262, 71, 31))
        self.lcdObwod.setObjectName("lcdObwod")

        self.line_przekatna_d2 = QtWidgets.QLineEdit(Deltoid)
        self.line_przekatna_d2.setGeometry(QtCore.QRect(160, 70, 113, 22))
        self.line_przekatna_d2.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_przekatna_d2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_przekatna_d2.setObjectName("line_przekatna_d2")
        self.line_przekatna_d2.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_przekatna_d2.setText('0')

        self.label_4 = QtWidgets.QLabel(Deltoid)
        self.label_4.setGeometry(QtCore.QRect(150, 30, 141, 31))
        self.label_4.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        #self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setLineWidth(1)
        self.label_4.setMidLineWidth(0)
        self.label_4.setWordWrap(False)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_4.setObjectName("label_4")

        self.line_przekatna_d1 = QtWidgets.QLineEdit(Deltoid)
        self.line_przekatna_d1.setGeometry(QtCore.QRect(30, 70, 113, 22))
        self.line_przekatna_d1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_przekatna_d1.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_przekatna_d1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_przekatna_d1.setText("")
        self.line_przekatna_d1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_przekatna_d1.setObjectName("line_przekatna_d1")
        self.line_przekatna_d1.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_przekatna_d1.setText('0')

        self.line_bok_a_2 = QtWidgets.QLineEdit(Deltoid)
        self.line_bok_a_2.setGeometry(QtCore.QRect(160, 140, 113, 22))
        self.line_bok_a_2.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_bok_a_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_bok_a_2.setObjectName("line_bok_a_2")
        self.line_bok_a_2.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_bok_a_2.setText('0')

        self.line_bok_a = QtWidgets.QLineEdit(Deltoid)
        self.line_bok_a.setGeometry(QtCore.QRect(30, 140, 113, 22))
        self.line_bok_a.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_bok_a.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_bok_a.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_bok_a.setText("")
        self.line_bok_a.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_bok_a.setObjectName("line_bok_a")
        self.line_bok_a.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_bok_a.setText('0')

        self.label_5 = QtWidgets.QLabel(Deltoid)
        self.label_5.setGeometry(QtCore.QRect(150, 100, 141, 31))
        self.label_5.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        #self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setLineWidth(1)
        self.label_5.setMidLineWidth(0)
        self.label_5.setWordWrap(False)
        self.label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(Deltoid)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 141, 31))
        self.label_6.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        #self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setLineWidth(1)
        self.label_6.setMidLineWidth(0)
        self.label_6.setWordWrap(False)
        self.label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Deltoid)
        QtCore.QMetaObject.connectSlotsByName(Deltoid)

    def retranslateUi(self, Deltoid):
        _translate = QtCore.QCoreApplication.translate
        Deltoid.setWindowTitle(_translate("Deltoid", "Deltoid"))
        self.label.setText(_translate("Deltoid", "Wpisz długość prz. d1"))
        self.obliczButton.setText(_translate("Deltoid", "Oblicz"))
        self.label_2.setText(_translate("Deltoid", "Pole deltoidu"))
        self.label_3.setText(_translate("Deltoid", "Obwód deltoidu"))
        self.label_4.setText(_translate("Deltoid", "Wpisz długość prz. d2"))
        self.label_5.setText(_translate("Deltoid", "Wpisz długość boku b"))
        self.label_6.setText(_translate("Deltoid", "Wpisz długość boku a"))

        self.obliczButton.clicked.connect(self.wykonaj)

    def wykonaj(self):
        bokA = self.line_bok_a.text()
        bokB = self.line_bok_a_2.text()
        d1 = self.line_przekatna_d1.text()
        d2 = self.line_przekatna_d2.text()

        pole = (1 / 2) * float(d1) * float(d2)
        obwod = 2*(float(bokA)) + 2*(float(bokB) )

        if (float(bokB) and float(bokA) and float(d1) and float(d2)) == 0:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Wpisałes błedną(e) wartość")
            msg.setInformativeText('Długość nie moze wynosic 0')
            msg.setWindowTitle("Błąd")
            msg.exec_()
        else:
            self.lcdPole.display(pole)
            self.lcdObwod.display(obwod)

