# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Help.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Help(object):
    def setupUi(self, Help):
        Help.setObjectName("Romb")
        Help.resize(300, 300)
        Help.setMinimumSize(QtCore.QSize(300, 300))
        Help.setMaximumSize(QtCore.QSize(300, 300))
        Help.setWindowIcon(QIcon('logo.png'))
        Help.setStyleSheet("background-image: url(tlopodstrony.png);")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Help)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 281))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.horizontalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 267, 277))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser.setGeometry(QtCore.QRect(0, -10, 271, 291))
        self.textBrowser.setStyleSheet("background:rgb(255, 255, 255)")
        self.textBrowser.setObjectName("textBrowser")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Help)
        QtCore.QMetaObject.connectSlotsByName(Help)

    def retranslateUi(self, Romb):
        _translate = QtCore.QCoreApplication.translate
        Romb.setWindowTitle(_translate("Romb", "Help"))
        self.textBrowser.setHtml(_translate("Romb", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Asap\'; font-size:8pt; color:#000000; background-color:#ffffff;\">**CREATED BY RAFAL SZCZEPANIK**                                                                                                                                     </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Asap\'; font-size:8pt; color:#000000;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Asap\'; font-size:8pt; color:#000000;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Asap\'; font-size:8pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Asap\'; font-size:8pt; color:#000000; background-color:#ffffff;\">Prezentowany kalkulator pozwala w bardzo łatwy sposób obliczyć parametry figur. Aby wykonać obliczenia należy wypełnić w odpowiednie pole znaną wartością a następnie wcisnąć przycisk </span><span style=\" font-family:\'Asap\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffff;\">OBLICZ</span><span style=\" font-family:\'Asap\'; font-size:8pt; color:#000000; background-color:#ffffff;\"> . Podane wyniki są wyświetlane z dokładnością do czterech miejsc po przecinku. Zapraszamy do korzystania z kalkulatora pól i objętości.</span></p>\n"
"<h2 style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Google Sans\',\'Roboto\',\'sans-serif\'; font-size:8pt; font-weight:600; color:#202124; background-color:#ffffff;\"><br /></h2>\n"
"<h2 style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Google Sans\',\'Roboto\',\'sans-serif\'; font-size:8pt; font-weight:600; color:#202124; background-color:#ffffff;\"><br /></h2>\n"
"<h2 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Asap\'; font-size:11pt; font-weight:600; color:#000000; background-color:#dfdfdf;\">Kalkulator obliczy te parametry, które możliwe są do obliczenia! Wprowadź w odpowiednie miejsca te dane, które masz. Kalkulator obliczy automatycznie pozostałe (możliwe do obliczenia przy takich danych) parametry.</span></h2>\n"
"<h2 style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Google Sans\',\'Roboto\',\'sans-serif\'; font-size:11pt; font-weight:600; color:#202124; background-color:#ffffff;\"><br /></h2>\n"
"<h2 style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Google Sans\',\'Roboto\',\'sans-serif\'; font-size:11pt; font-weight:600; color:#202124; background-color:#ffffff;\"><br /></h2>\n"
"<h2 style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Google Sans\',\'Roboto\',\'sans-serif\'; font-size:11pt; font-weight:600; color:#202124; background-color:#ffffff;\"><br /></h2>\n"
"<h2 style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Google Sans\',\'Roboto\',\'sans-serif\'; font-size:11pt; font-weight:600; color:#202124; background-color:#ffffff;\"><br /></h2>\n"
"<h2 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Google Sans\',\'Roboto\',\'sans-serif\'; font-size:11pt; font-weight:600; color:#202124; background-color:#ffffff;\">Prześlij opinię</span></h2>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Roboto\',\'Helvetica Neue\',\'Helvetica\',\'sans-serif\'; font-size:8pt; color:#3c4043; background-color:#ffffff;\">Jeśli wyświetli się nieprawidłowy wynik lub chcesz zaproponować nowy typ obliczenia, przeslij opinie na maila rafal.szczepanik17@gmail.com</span></p></body></html>"))
