# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kwadrat.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kwadrat(object):
    def setupUi(self, Kwadrat):
        Kwadrat.setObjectName("Kwadrat")
        Kwadrat.resize(300, 300)
        Kwadrat.setMinimumSize(QtCore.QSize(300, 300))
        Kwadrat.setMaximumSize(QtCore.QSize(300, 300))
        Kwadrat.setStyleSheet("background:rgb(11, 198, 205)")
        self.label = QtWidgets.QLabel(Kwadrat)
        self.label.setGeometry(QtCore.QRect(50, 30, 181, 31))
        self.label.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setWordWrap(False)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Kwadrat)
        self.lineEdit.setGeometry(QtCore.QRect(80, 70, 113, 22))
        self.lineEdit.setStyleSheet("background:rgb(255, 255, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Kwadrat)
        self.pushButton.setGeometry(QtCore.QRect(90, 120, 93, 28))
        self.pushButton.setStyleSheet("background:rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Kwadrat)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 101, 31))
        self.label_2.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(1)
        self.label_2.setMidLineWidth(0)
        self.label_2.setWordWrap(False)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Kwadrat)
        self.label_3.setGeometry(QtCore.QRect(170, 170, 111, 31))
        self.label_3.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setLineWidth(1)
        self.label_3.setMidLineWidth(0)
        self.label_3.setWordWrap(False)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")
        self.lcdNumber = QtWidgets.QLCDNumber(Kwadrat)
        self.lcdNumber.setGeometry(QtCore.QRect(40, 220, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Kwadrat)
        self.lcdNumber_2.setGeometry(QtCore.QRect(190, 220, 64, 23))
        self.lcdNumber_2.setObjectName("lcdNumber_2")

        self.retranslateUi(Kwadrat)
        QtCore.QMetaObject.connectSlotsByName(Kwadrat)

    def retranslateUi(self, Kwadrat):
        _translate = QtCore.QCoreApplication.translate
        Kwadrat.setWindowTitle(_translate("Kwadrat", "Form"))
        self.label.setText(_translate("Kwadrat", "Wpisz długość boku kwadratu"))
        self.pushButton.setText(_translate("Kwadrat", "Oblicz"))
        self.label_2.setText(_translate("Kwadrat", "Pole kwadratu"))
        self.label_3.setText(_translate("Kwadrat", "Obwód kwadratu"))
