# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prostokat.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtWidgets import QMessageBox


class Ui_Prostokat(object):
    def setupUi(self, Prostokat):
        Prostokat.setObjectName("Prostokat")
        Prostokat.resize(300, 300)
        Prostokat.setMinimumSize(QtCore.QSize(300, 300))
        Prostokat.setMaximumSize(QtCore.QSize(300, 300))
        Prostokat.setStyleSheet("background:rgb(11, 198, 205)")

        self.label = QtWidgets.QLabel(Prostokat)
        self.label.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.label.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setWordWrap(False)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")

        self.obliczButton = QtWidgets.QPushButton(Prostokat)
        self.obliczButton.setGeometry(QtCore.QRect(100, 120, 93, 28))
        self.obliczButton.setStyleSheet("background:rgb(255, 255, 255)")
        self.obliczButton.setObjectName("obliczButton")

        self.label_2 = QtWidgets.QLabel(Prostokat)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 101, 31))
        self.label_2.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(1)
        self.label_2.setMidLineWidth(0)
        self.label_2.setWordWrap(False)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(Prostokat)
        self.label_3.setGeometry(QtCore.QRect(170, 170, 121, 31))
        self.label_3.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setLineWidth(1)
        self.label_3.setMidLineWidth(0)
        self.label_3.setWordWrap(False)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")

        self.lcdPoleProst = QtWidgets.QLCDNumber(Prostokat)
        self.lcdPoleProst.setGeometry(QtCore.QRect(40, 220, 64, 23))
        self.lcdPoleProst.setObjectName("lcdPoleProst")

        self.lcdObwodProst = QtWidgets.QLCDNumber(Prostokat)
        self.lcdObwodProst.setGeometry(QtCore.QRect(190, 220, 64, 23))
        self.lcdObwodProst.setObjectName("lcdObwodProst")

        self.lineEdit_bok_b = QtWidgets.QLineEdit(Prostokat)
        self.lineEdit_bok_b.setGeometry(QtCore.QRect(160, 70, 113, 22))
        self.lineEdit_bok_b.setStyleSheet("background:rgb(255, 255, 255)")
        self.lineEdit_bok_b.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lineEdit_bok_b.setObjectName("lineEdit_bok_b")
        self.lineEdit_bok_b.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.lineEdit_bok_b.setText('0')

        self.label_4 = QtWidgets.QLabel(Prostokat)
        self.label_4.setGeometry(QtCore.QRect(150, 30, 141, 31))
        self.label_4.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setLineWidth(1)
        self.label_4.setMidLineWidth(0)
        self.label_4.setWordWrap(False)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_4.setObjectName("label_4")

        self.lineEdit_bok_a = QtWidgets.QLineEdit(Prostokat)
        self.lineEdit_bok_a.setGeometry(QtCore.QRect(30, 70, 113, 22))
        self.lineEdit_bok_a.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_bok_a.setStyleSheet("background:rgb(255, 255, 255)")
        self.lineEdit_bok_a.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lineEdit_bok_a.setObjectName("lineEdit_bok_a")
       # self.lineEdit_bok_a.setValidator(QtGui.QIntValidator(1, 999))
        self.lineEdit_bok_a.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.lineEdit_bok_a.setText('0')

        self.retranslateUi(Prostokat)
        QtCore.QMetaObject.connectSlotsByName(Prostokat)

        self.obliczButton.clicked.connect(self.wykonaj)



    def retranslateUi(self, Prostokat):
        _translate = QtCore.QCoreApplication.translate
        Prostokat.setWindowTitle(_translate("Prostokat", "POSTOKĄT"))
        self.label.setText(_translate("Prostokat", "Wpisz długość boku a"))
        self.obliczButton.setText(_translate("Prostokat", "Oblicz"))
        self.label_2.setText(_translate("Prostokat", "Pole prostokąta"))
        self.label_3.setText(_translate("Prostokat", "Obwód prostokota"))
        self.label_4.setText(_translate("Prostokat", "Wpisz długość boku b"))

    def wykonaj(self):
        zmienna1 = self.lineEdit_bok_a.text()
        zmienna2 = self.lineEdit_bok_b.text()

        poleprostokota = float(zmienna1) * float(zmienna2)
        obwodprostokata = (float(zmienna1) * 2) + (float(zmienna2)*2)


        if (float(zmienna1) and float(zmienna2)) == 0:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Wpisałes błedną(e) wartość")
            msg.setInformativeText('Długość nie moze wynosic 0')
            msg.setWindowTitle("Błąd")
            msg.exec_()
        else:
            self.lcdPoleProst.display(poleprostokota)
            self.lcdObwodProst.display(obwodprostokata)
