# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rownloleglobok.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtWidgets import QMessageBox


class Ui_Rownoleglobok(object):
    def setupUi(self, Rownoleglobok):
        Rownoleglobok.setObjectName("Rownoleglobok")
        Rownoleglobok.resize(300, 300)
        Rownoleglobok.setMinimumSize(QtCore.QSize(300, 300))
        Rownoleglobok.setMaximumSize(QtCore.QSize(300, 300))
        Rownoleglobok.setStyleSheet("background:rgb(11, 198, 205)")

        self.label = QtWidgets.QLabel(Rownoleglobok)
        self.label.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.label.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setWordWrap(False)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")

        self.obliczButton = QtWidgets.QPushButton(Rownoleglobok)
        self.obliczButton.setGeometry(QtCore.QRect(110, 170, 93, 28))
        self.obliczButton.setStyleSheet("background:rgb(255, 255, 255)")
        self.obliczButton.setObjectName("obliczButton")

        self.label_2 = QtWidgets.QLabel(Rownoleglobok)
        self.label_2.setGeometry(QtCore.QRect(10, 220, 131, 31))
        self.label_2.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(1)
        self.label_2.setMidLineWidth(0)
        self.label_2.setWordWrap(False)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(Rownoleglobok)
        self.label_3.setGeometry(QtCore.QRect(140, 220, 151, 31))
        self.label_3.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setLineWidth(1)
        self.label_3.setMidLineWidth(0)
        self.label_3.setWordWrap(False)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")

        self.lcdPole = QtWidgets.QLCDNumber(Rownoleglobok)
        self.lcdPole.setGeometry(QtCore.QRect(40, 260, 81, 31))
        self.lcdPole.setObjectName("lcdPole")

        self.lineEdit_wysokosc = QtWidgets.QLineEdit(Rownoleglobok)
        self.lineEdit_wysokosc.setGeometry(QtCore.QRect(160, 70, 113, 22))
        self.lineEdit_wysokosc.setStyleSheet("background:rgb(255, 255, 255)")
        self.lineEdit_wysokosc.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lineEdit_wysokosc.setObjectName("lineEdit_wysokosc")
        self.lineEdit_wysokosc.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.lineEdit_wysokosc.setText('0')

        self.label_4 = QtWidgets.QLabel(Rownoleglobok)
        self.label_4.setGeometry(QtCore.QRect(160, 30, 121, 31))
        self.label_4.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setLineWidth(1)
        self.label_4.setMidLineWidth(0)
        self.label_4.setWordWrap(False)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_4.setObjectName("label_4")

        self.LineEdit_bok_a = QtWidgets.QLineEdit(Rownoleglobok)
        self.LineEdit_bok_a.setGeometry(QtCore.QRect(30, 70, 113, 22))
        self.LineEdit_bok_a.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LineEdit_bok_a.setStyleSheet("background:rgb(255, 255, 255)")
        self.LineEdit_bok_a.setInputMethodHints(QtCore.Qt.ImhNone)
        self.LineEdit_bok_a.setText("")
        self.LineEdit_bok_a.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.LineEdit_bok_a.setObjectName("LineEdit_bok_a")
        self.LineEdit_bok_a.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.LineEdit_bok_a.setText('0')

        self.label_5 = QtWidgets.QLabel(Rownoleglobok)
        self.label_5.setGeometry(QtCore.QRect(80, 100, 141, 31))
        self.label_5.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setLineWidth(1)
        self.label_5.setMidLineWidth(0)
        self.label_5.setWordWrap(False)
        self.label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_5.setObjectName("label_5")

        self.lineEdit_bok_b = QtWidgets.QLineEdit(Rownoleglobok)
        self.lineEdit_bok_b.setGeometry(QtCore.QRect(100, 140, 113, 22))
        self.lineEdit_bok_b.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_bok_b.setStyleSheet("background:rgb(255, 255, 255)")
        self.lineEdit_bok_b.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_bok_b.setText("")
        self.lineEdit_bok_b.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lineEdit_bok_b.setObjectName("lineEdit_bok_b")
        self.lineEdit_bok_b.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.lineEdit_bok_b.setText('0')

        self.lcdObwod = QtWidgets.QLCDNumber(Rownoleglobok)
        self.lcdObwod.setGeometry(QtCore.QRect(170, 260, 81, 31))
        self.lcdObwod.setObjectName("lcdObwod")

        self.retranslateUi(Rownoleglobok)
        QtCore.QMetaObject.connectSlotsByName(Rownoleglobok)

    def retranslateUi(self, Rownoleglobok):
        _translate = QtCore.QCoreApplication.translate
        Rownoleglobok.setWindowTitle(_translate("Rownoleglobok", "Równoległobok"))
        self.label.setText(_translate("Rownoleglobok", "Wpisz długość boku a"))
        self.obliczButton.setText(_translate("Rownoleglobok", "Oblicz"))
        self.label_2.setText(_translate("Rownoleglobok", "Pole rownoległoboku"))
        self.label_3.setText(_translate("Rownoleglobok", "Obwód rownoległoboku"))
        self.label_4.setText(_translate("Rownoleglobok", "Wpisz wysokość"))
        self.label_5.setText(_translate("Rownoleglobok", "Wpisz długość boku b"))

        self.obliczButton.clicked.connect(self.wykonaj)

    def wykonaj(self):
        bokA = self.LineEdit_bok_a.text()
        bokB = self.lineEdit_bok_b.text()
        wys = self.lineEdit_wysokosc.text()

        pole = float(bokA) * float(wys)
        obwod = (2*(float(bokA))) + (2*(float(bokB)))

        if (float(bokB) and float(bokA) and float(wys)) == 0:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Wpisałes błedną(e) wartość")
            msg.setInformativeText('Długość nie moze wynosic 0')
            msg.setWindowTitle("Błąd")
            msg.exec_()
        else:
            self.lcdPole.display(pole)
            self.lcdObwod.display(obwod)