# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rownoboczny.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator, QIcon
from PyQt5.QtWidgets import QMessageBox


class Ui_Rownoboczny(object):
    def setupUi(self, Rownoboczny):
        Rownoboczny.setObjectName("Rownoboczny")
        Rownoboczny.resize(300, 300)
        Rownoboczny.setMinimumSize(QtCore.QSize(300, 300))
        Rownoboczny.setMaximumSize(QtCore.QSize(300, 300))
        Rownoboczny.setWindowIcon(QIcon('logo.png'))
        Rownoboczny.setStyleSheet("background-image: url(tlopodstrony.png);")

        self.label = QtWidgets.QLabel(Rownoboczny)
        self.label.setGeometry(QtCore.QRect(90, 30, 121, 31))
        self.label.setStyleSheet("background:rgb(255, 255, 255)")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
       # self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setWordWrap(False)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")

        self.lineEdit = QtWidgets.QLineEdit(Rownoboczny)
        self.lineEdit.setGeometry(QtCore.QRect(90, 70, 113, 22))
        self.lineEdit.setStyleSheet("background:rgb(255, 255, 255)")
        self.lineEdit.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        #self.lineEdit.setValidator(QtGui.QIntValidator(1, 999))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.lineEdit.setText('0')

        self.obliczButton = QtWidgets.QPushButton(Rownoboczny)
        self.obliczButton.setGeometry(QtCore.QRect(100, 120, 93, 28))
        self.obliczButton.setStyleSheet("background:rgb(255, 255, 255)")
        self.obliczButton.setObjectName("obliczButton")

        self.label_2_pole = QtWidgets.QLabel(Rownoboczny)
        self.label_2_pole.setGeometry(QtCore.QRect(20, 170, 101, 31))
        self.label_2_pole.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_2_pole.setFrameShape(QtWidgets.QFrame.Box)
        #self.label_2_pole.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2_pole.setLineWidth(1)
        self.label_2_pole.setMidLineWidth(0)
        self.label_2_pole.setWordWrap(False)
        self.label_2_pole.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_2_pole.setObjectName("label_2_pole")

        self.label_3_obwod = QtWidgets.QLabel(Rownoboczny)
        self.label_3_obwod.setGeometry(QtCore.QRect(170, 170, 111, 31))
        self.label_3_obwod.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_3_obwod.setFrameShape(QtWidgets.QFrame.Box)
        #self.label_3_obwod.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3_obwod.setLineWidth(1)
        self.label_3_obwod.setMidLineWidth(0)
        self.label_3_obwod.setWordWrap(False)
        self.label_3_obwod.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3_obwod.setObjectName("label_3_obwod")

        self.lcdPole = QtWidgets.QLCDNumber(Rownoboczny)
        self.lcdPole.setGeometry(QtCore.QRect(40, 220, 64, 23))
        self.lcdPole.setObjectName("lcdPole")

        self.lcdObwod = QtWidgets.QLCDNumber(Rownoboczny)
        self.lcdObwod.setGeometry(QtCore.QRect(190, 220, 64, 23))
        self.lcdObwod.setObjectName("lcdObwod")

        self.retranslateUi(Rownoboczny)
        QtCore.QMetaObject.connectSlotsByName(Rownoboczny)

    def retranslateUi(self, Rownoboczny):
        _translate = QtCore.QCoreApplication.translate
        Rownoboczny.setWindowTitle(_translate("Rownoboczny", "RÓWNOBOCZNY"))
        self.label.setText(_translate("Rownoboczny", "Wpisz długość boku"))
        self.obliczButton.setText(_translate("Rownoboczny", "Oblicz"))
        self.label_2_pole.setText(_translate("Rownoboczny", "Pole trójkąta"))
        self.label_3_obwod.setText(_translate("Rownoboczny", "Obwód trójkąta"))

        self.obliczButton.clicked.connect(self.wykonaj)

    def wykonaj(self):
        zmienna1 = self.lineEdit.text()
        pom = 1 / 4

        pole = pom * (float(zmienna1) * float(zmienna1)) * 1.73
        obwod = float(zmienna1)*3


        if (float(zmienna1)) == 0:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Wpisałes błedną(e) wartość")
            msg.setInformativeText('Długość nie moze wynosic 0')
            msg.setWindowTitle("Błąd")
            msg.exec_()
        else:
            self.lcdPole.display(pole)
            self.lcdObwod.display(obwod)

