# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Roznoboczny.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtWidgets import QMessageBox


class Ui_Roznoboczny(object):
    def setupUi(self, Roznoboczny):
        Roznoboczny.setObjectName("Roznoboczny")
        Roznoboczny.resize(300, 300)
        Roznoboczny.setMinimumSize(QtCore.QSize(300, 300))
        Roznoboczny.setMaximumSize(QtCore.QSize(300, 300))
        Roznoboczny.setStyleSheet("background:rgb(11, 198, 205)")

        self.label = QtWidgets.QLabel(Roznoboczny)
        self.label.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.label.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setWordWrap(False)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")

        self.obliczButton = QtWidgets.QPushButton(Roznoboczny)
        self.obliczButton.setGeometry(QtCore.QRect(100, 180, 93, 28))
        self.obliczButton.setStyleSheet("background:rgb(255, 255, 255)")
        self.obliczButton.setObjectName("obliczButton")

        self.label_2 = QtWidgets.QLabel(Roznoboczny)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 101, 31))
        self.label_2.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(1)
        self.label_2.setMidLineWidth(0)
        self.label_2.setWordWrap(False)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(Roznoboczny)
        self.label_3.setGeometry(QtCore.QRect(170, 220, 121, 31))
        self.label_3.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setLineWidth(1)
        self.label_3.setMidLineWidth(0)
        self.label_3.setWordWrap(False)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")

        self.lcdPole = QtWidgets.QLCDNumber(Roznoboczny)
        self.lcdPole.setGeometry(QtCore.QRect(40, 270, 64, 23))
        self.lcdPole.setObjectName("lcdPole")



        self.lcdObwod = QtWidgets.QLCDNumber(Roznoboczny)
        self.lcdObwod.setGeometry(QtCore.QRect(190, 270, 64, 23))
        self.lcdObwod.setObjectName("lcdObwod")

        self.line_bok_b = QtWidgets.QLineEdit(Roznoboczny)
        self.line_bok_b.setGeometry(QtCore.QRect(160, 70, 113, 22))
        self.line_bok_b.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_bok_b.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_bok_b.setObjectName("line_bok_b")
       # self.line_bok_b.setValidator(QtGui.QIntValidator(1, 999))
        self.line_bok_b.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_bok_b.setText('0')

        self.label_4 = QtWidgets.QLabel(Roznoboczny)
        self.label_4.setGeometry(QtCore.QRect(150, 30, 141, 31))
        self.label_4.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setLineWidth(1)
        self.label_4.setMidLineWidth(0)
        self.label_4.setWordWrap(False)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_4.setObjectName("label_4")

        self.line_bok_a = QtWidgets.QLineEdit(Roznoboczny)
        self.line_bok_a.setGeometry(QtCore.QRect(30, 70, 113, 22))
        self.line_bok_a.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_bok_a.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_bok_a.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_bok_a.setText("")
        self.line_bok_a.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_bok_a.setObjectName("line_bok_a")
       # self.line_bok_a.setValidator(QtGui.QIntValidator(1, 999))
        self.line_bok_a.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_bok_a.setText('0')



        self.line_wysokosc_2 = QtWidgets.QLineEdit(Roznoboczny)
        self.line_wysokosc_2.setGeometry(QtCore.QRect(160, 140, 113, 22))
        self.line_wysokosc_2.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_wysokosc_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_wysokosc_2.setObjectName("line_wysokosc_2")
        #self.line_wysokosc_2.setValidator(QtGui.QIntValidator(1, 999))
        self.line_wysokosc_2.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_wysokosc_2.setText('0')

        self.line_bok_c = QtWidgets.QLineEdit(Roznoboczny)
        self.line_bok_c.setGeometry(QtCore.QRect(30, 140, 113, 22))
        self.line_bok_c.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_bok_c.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_bok_c.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_bok_c.setText("")
        self.line_bok_c.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_bok_c.setObjectName("line_bok_c")
        #self.line_bok_c.setValidator(QtGui.QIntValidator(1, 999))
        self.line_bok_c.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_bok_c.setText('0')

        self.label_5 = QtWidgets.QLabel(Roznoboczny)
        self.label_5.setGeometry(QtCore.QRect(150, 100, 141, 31))
        self.label_5.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setLineWidth(1)
        self.label_5.setMidLineWidth(0)
        self.label_5.setWordWrap(False)
        self.label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(Roznoboczny)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 141, 31))
        self.label_6.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setLineWidth(1)
        self.label_6.setMidLineWidth(0)
        self.label_6.setWordWrap(False)
        self.label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Roznoboczny)
        QtCore.QMetaObject.connectSlotsByName(Roznoboczny)

    def retranslateUi(self, Roznoboczny):
        _translate = QtCore.QCoreApplication.translate
        Roznoboczny.setWindowTitle(_translate("Roznoboczny", "Rożnoboczny"))
        self.label.setText(_translate("Roznoboczny", "Wpisz długość boku a"))
        self.obliczButton.setText(_translate("Roznoboczny", "Oblicz"))
        self.label_2.setText(_translate("Roznoboczny", "Pole rombu"))
        self.label_3.setText(_translate("Roznoboczny", "Obwód rombu"))
        self.label_4.setText(_translate("Roznoboczny", "Wpisz długość boku b"))
        self.label_5.setText(_translate("Roznoboczny", "Wpisz wysokość"))
        self.label_6.setText(_translate("Roznoboczny", "Wpisz długość boku c"))

        self.obliczButton.clicked.connect(self.wykonaj)



    def wykonaj(self):
        bokA = self.line_bok_a.text()
        bokB = self.line_bok_b.text()
        bokC = self.line_bok_c.text()
        wys = self.line_wysokosc_2.text()

        pole = (1 / 2 ) *float(bokA) * float(wys)
        obwod = float(bokA)+float(bokB)+float(bokC)



        if (float(bokB) and float(bokA) and float(bokC) and float(wys )) == 0:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Wpisałes błedną(e) wartość")
            msg.setInformativeText('Długość nie moze wynosic 0')
            msg.setWindowTitle("Błąd")
            msg.exec_()
        else:
            self.lcdPole.display(pole)
            self.lcdObwod.display(obwod)









