# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Trapez.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtWidgets import QMessageBox


class Ui_Trapez(object):
    def setupUi(self, Trapez):
        Trapez.setObjectName("Trapez")
        Trapez.resize(300, 300)
        Trapez.setMinimumSize(QtCore.QSize(300, 300))
        Trapez.setMaximumSize(QtCore.QSize(300, 300))
        Trapez.setStyleSheet("background:rgb(11, 198, 205)")

        self.label = QtWidgets.QLabel(Trapez)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 31))
        self.label.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setWordWrap(False)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")

        self.obliczButton = QtWidgets.QPushButton(Trapez)
        self.obliczButton.setGeometry(QtCore.QRect(170, 170, 93, 28))
        self.obliczButton.setStyleSheet("background:rgb(255, 255, 255)")
        self.obliczButton.setObjectName("obliczButton")

        self.label_2 = QtWidgets.QLabel(Trapez)
        self.label_2.setGeometry(QtCore.QRect(30, 220, 111, 31))
        self.label_2.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(1)
        self.label_2.setMidLineWidth(0)
        self.label_2.setWordWrap(False)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(Trapez)
        self.label_3.setGeometry(QtCore.QRect(160, 220, 121, 31))
        self.label_3.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setLineWidth(1)
        self.label_3.setMidLineWidth(0)
        self.label_3.setWordWrap(False)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")

        self.lcdPole = QtWidgets.QLCDNumber(Trapez)
        self.lcdPole.setGeometry(QtCore.QRect(40, 260, 81, 31))
        self.lcdPole.setObjectName("lcdPole")

        self.line_bok_b = QtWidgets.QLineEdit(Trapez)
        self.line_bok_b.setGeometry(QtCore.QRect(160, 50, 113, 22))
        self.line_bok_b.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_bok_b.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_bok_b.setObjectName("line_bok_b")
        self.line_bok_b.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_bok_b.setText('0')

        self.label_4 = QtWidgets.QLabel(Trapez)
        self.label_4.setGeometry(QtCore.QRect(150, 10, 141, 31))
        self.label_4.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setLineWidth(1)
        self.label_4.setMidLineWidth(0)
        self.label_4.setWordWrap(False)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_4.setObjectName("label_4")

        self.line_bok_a = QtWidgets.QLineEdit(Trapez)
        self.line_bok_a.setGeometry(QtCore.QRect(30, 50, 113, 22))
        self.line_bok_a.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_bok_a.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_bok_a.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_bok_a.setText("")
        self.line_bok_a.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_bok_a.setObjectName("line_bok_a")
        self.line_bok_a.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_bok_a.setText('0')

        self.line_wysokosc_2 = QtWidgets.QLineEdit(Trapez)
        self.line_wysokosc_2.setGeometry(QtCore.QRect(30, 190, 113, 22))
        self.line_wysokosc_2.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_wysokosc_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_wysokosc_2.setObjectName("line_wysokosc_2")
        self.line_wysokosc_2.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_wysokosc_2.setText('0')

        self.line_bok_c = QtWidgets.QLineEdit(Trapez)
        self.line_bok_c.setGeometry(QtCore.QRect(30, 120, 113, 22))
        self.line_bok_c.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_bok_c.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_bok_c.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_bok_c.setText("")
        self.line_bok_c.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_bok_c.setObjectName("line_bok_c")
        self.line_bok_c.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_bok_c.setText('0')

        self.label_5 = QtWidgets.QLabel(Trapez)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 141, 31))
        self.label_5.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setLineWidth(1)
        self.label_5.setMidLineWidth(0)
        self.label_5.setWordWrap(False)
        self.label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(Trapez)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 141, 31))
        self.label_6.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setLineWidth(1)
        self.label_6.setMidLineWidth(0)
        self.label_6.setWordWrap(False)
        self.label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_6.setObjectName("label_6")

        self.line_bok_d = QtWidgets.QLineEdit(Trapez)
        self.line_bok_d.setGeometry(QtCore.QRect(160, 120, 113, 22))
        self.line_bok_d.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_bok_d.setStyleSheet("background:rgb(255, 255, 255)")
        self.line_bok_d.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_bok_d.setText("")
        self.line_bok_d.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_bok_d.setObjectName("line_bok_d")
        self.line_bok_d.setValidator(QRegExpValidator(QRegExp("[0.1-9.9]*")))
        self.line_bok_d.setText('0')

        self.label_7 = QtWidgets.QLabel(Trapez)
        self.label_7.setGeometry(QtCore.QRect(150, 80, 141, 31))
        self.label_7.setStyleSheet("labelcolor:rgb(204, 204, 204)")
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_7.setLineWidth(1)
        self.label_7.setMidLineWidth(0)
        self.label_7.setWordWrap(False)
        self.label_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_7.setObjectName("label_7")

        self.lcdObwod = QtWidgets.QLCDNumber(Trapez)
        self.lcdObwod.setGeometry(QtCore.QRect(180, 260, 81, 31))
        self.lcdObwod.setObjectName("lcdObwod")

        self.retranslateUi(Trapez)
        QtCore.QMetaObject.connectSlotsByName(Trapez)

    def retranslateUi(self, Trapez):
        _translate = QtCore.QCoreApplication.translate
        Trapez.setWindowTitle(_translate("Trapez", "Trapez"))
        self.label.setText(_translate("Trapez", "Wpisz długość boku a"))
        self.obliczButton.setText(_translate("Trapez", "Oblicz"))
        self.label_2.setText(_translate("Trapez", "Pole trapezu"))
        self.label_3.setText(_translate("Trapez", "Obwód trapezu"))
        self.label_4.setText(_translate("Trapez", "Wpisz długość boku b"))
        self.label_5.setText(_translate("Trapez", "Wpisz wysokość"))
        self.label_6.setText(_translate("Trapez", "Wpisz długość boku c"))
        self.label_7.setText(_translate("Trapez", "Wpisz długość boku d"))

        self.obliczButton.clicked.connect(self.wykonaj)

    def wykonaj(self):
        bokA = self.line_bok_a.text()
        bokB = self.line_bok_b.text()
        bokC = self.line_bok_c.text()
        bokD= self.line_bok_d.text()
        wys = self.line_wysokosc_2.text()

        pole = (1 / 2) * ((float(bokA) + float(bokB)) * float(wys))
        obwod = float(bokA) + float(bokB) + float(bokC)+ float(bokD)

        if (float(bokB) and float(bokA) and float(bokC)and float(bokD) and float(wys)) == 0:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Wpisałes błedną(e) wartość")
            msg.setInformativeText('Długość nie moze wynosic 0')
            msg.setWindowTitle("Błąd")
            msg.exec_()
        else:
            self.lcdPole.display(pole)
            self.lcdObwod.display(obwod)
